[package]
name = "rust_gba_emu"
version = "0.1.0"
edition = "2021"

[dependencies]
log = {version = "0.4", optional = true}
simple_logger = { version = "1.16", optional = true }

[features]
logging = ["log", "simple_logger"]